name: "Publish to marketplace"
description: "Publish to marketplace"

runs:
    using: "composite"
    steps:
        - name: Publish to marketplace
          run: |
              if [ -n "$(git status --porcelain)" ]; then
                echo "Working directory is not clean. Committing changes..."
                git add .
                git commit -m "Automated commit by GitHub Actions"
              fi

              vsce publish patch -m "%s-pre-release" --pre-release
              git push
              git push origin --tags
          env:
              VSCE_PAT: ${{ secrets.VSCE_PAT }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
