name: "Build and Publish (pre-release)"

on:
    push:
        branches: ["pre-release"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/install-nodejs-and-packages

            - name: Update version
              id: update-version
              uses: ./.github/actions/update-version
              with:
                  update_semantic: "patch"

            - name: Build (pre-release)
              id: build
              uses: ./.github/actions/build-pre-release
              with:
                  is_pre_release: true
                  save_artifacts: true
                  push_changes: true
                  tag: ${{ steps.update-version.outputs.tag }}

            - name: Publish to marketplace
              uses: ./.github/actions/publish-to-marketplace
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  pre_release: true
                  tag: ${{ steps.update-version.outputs.tag }}
