name: Sample CI

on:
    push:
        branches: ["pre-release"]
    pull_request:
        branches: ["pre-release"]

jobs:
    # build:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4

    #         - name: Install Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: 18.x

    #         - name: Install packages
    #           run: |
    #               npm install
    #               npm install -g @vscode/vsce

    #         - name: Build
    #           run: |
    #               tag=$(npm --no-git-tag-version version patch)
    #               vsce package --pre-release

    #         - name: Save extension artifacts
    #           uses: actions/upload-artifact@v4
    #           with:
    #               name: Extension file (VSIX)
    #               path: "./*.vsix"

    publish:
        # needs: build
        # runs-on: ubuntu-latest
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.14.0

            - name: Install packages
              run: |
                  npm install
                  npm install -g @vscode/vsce

            - name: Publish to marketplace
              shell: cmd
              # run: |
              #     git config user.name "github-actions[bot]"
              #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              #     git status
              #     if git status --porcelain | findstr . >nul; then
              #       echo Working directory is not clean. Committing changes...
              #       git add .
              #       git commit -m "Automated commit by GitHub Actions"
              #     fi
              #     git status
              #     vsce publish patch -m "%s-pre-release" --pre-release
              #     git push origin --tags
              run: |
                  vsce publish --pre-release
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
