name: Sample CI

on:
    push:
        branches: ["pre-release"]
    pull_request:
        branches: ["pre-release"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x

            - name: Install packages
              run: |
                  npm install
                  npm install -g @vscode/vsce

            - name: Build
              run: |
                  tag=$(npm --no-git-tag-version version patch)
                  vsce package --pre-release

            - name: Save vsix
              uses: actions/upload-artifact@v4
              with:
                  name: vsix
                  path: "./*.vsix"

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Publish to marketplace
              run: vsce publish patch -m "%s-pre-release" --pre-release
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}

            - name: Push tag to git
              run: git push
